apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-site
  template:
    metadata:
      labels:
        app: devops-site
    spec:
      containers:
      - name: devops-site
        image: mateusamauri/devops-site
        ports:
        - containerPort: 80