name: CI/CD Docker + Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build da imagem Docker
      run: |
        docker build -t mateusamauri/devops-site:latest .

    - name: Push para o Docker Hub
      run: |
        docker push mateusamauri/devops-site:latest

    - name: Instalar kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Aplicar manifestos Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
